import 'tailwindcss/tailwind.css';
import 'flowbite/dist/flowbite.css';

export const metadata = {
  title: 'Next.js Complete Authentication',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="max-w-screen-xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  )
}
